src/Entity/Call.php
<?php

namespace App\Entity;

use App\Repository\CallRepository;
use App\Service\CallTreatmentDataMaker;
use \DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CallRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="`call`")
 */
class Call
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="calls",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Vehicle::class, inversedBy="calls", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $vehicle;

    /**
     * @ORM\ManyToOne(targetEntity=Subject::class, inversedBy="calls", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $subject;

    /**
     * @ORM\ManyToOne(targetEntity=Comment::class, inversedBy="calls", cascade={"persist"})
     */
    private $comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isUrgent;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isProcessEnded;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isAppointmentTaken;

    /**
     * @ORM\ManyToOne(targetEntity=Service::class, inversedBy="calls", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $service;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="date")
     */
    private $recallDate;

    /**
     * @ORM\Column(type="time")
     */
    private $recallHour;


    /**
     * @ORM\ManyToOne(targetEntity=RecallPeriod::class, inversedBy="calls", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $recallPeriod;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $freeComment;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $source;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $internet;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isProcessed;

    /**
     * @ORM\OneToMany(targetEntity=CallTransfer::class, mappedBy="referedCall", orphanRemoval=true)
     */
    private $callTransfers;

    /**
     * @ORM\OneToMany(targetEntity=CallProcessing::class, mappedBy="referedCall",
     *     orphanRemoval=true)
     */
    private $callProcessings;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="calls")
     * @ORM\JoinColumn(nullable=true)
     */
    private $recipient;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="callsUserCreate")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $appointmentDate;

    private $cityTransfer = 0;
    private $concessionTransfer = 0;
    private $serviceTransfer = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $clientCallback = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $origin;

    /**
     * @return mixed
     */
    public function getCityTransfer()
    {
        return $this->cityTransfer;
    }

    /**
     * @param mixed $cityTransfer
     */
    public function setCityTransfer($cityTransfer): void
    {
        $this->cityTransfer = $cityTransfer;
    }

    /**
     * @return mixed
     */
    public function getConcessionTransfer()
    {
        return $this->concessionTransfer;
    }

    /**
     * @param mixed $concessionTransfer
     */
    public function setConcessionTransfer($concessionTransfer): void
    {
        $this->concessionTransfer = $concessionTransfer;
    }

    /**
     * @return mixed
     */
    public function getServiceTransfer()
    {
        return $this->serviceTransfer;
    }

    /**
     * @param mixed $serviceTransfer
     */
    public function setServiceTransfer($serviceTransfer): void
    {
        $this->serviceTransfer = $serviceTransfer;
    }


    public function __construct()
    {
        $this->callTransfers = new ArrayCollection();
        $this->callProcessings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function getConcession()
    {
        if ($this->getService()) {
            return $this->getService()->getConcession();
        }
    }

    public function getCity()
    {
        if ($this->getConcession()) {
            return $this->getConcession()->getTown();
        }
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;
        return $this;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): self
    {
        $this->vehicle = $vehicle;
        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getComment(): ?Comment
    {
        return $this->comment;
    }

    public function setComment(?Comment $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getIsUrgent(): ?bool
    {
        return $this->isUrgent;
    }

    public function setIsUrgent(bool $isUrgent): self
    {
        $this->isUrgent = $isUrgent;

        return $this;
    }

    public function getIsProcessEnded(): ?bool
    {
        return $this->isProcessEnded;
    }

    public function setIsProcessEnded(bool $isProcessEnded): self
    {
        $this->isProcessEnded = $isProcessEnded;

        return $this;
    }

    public function setIsProcessEndedToNull(): self
    {
        $this->isProcessEnded = null;

        return $this;
    }

    public function getIsAppointmentTaken(): ?bool
    {
        return $this->isAppointmentTaken;
    }

    public function setIsAppointmentTaken(bool $isAppointmentTaken): self
    {
        $this->isAppointmentTaken = $isAppointmentTaken;

        return $this;
    }


    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist
     * @return $this
     * @throws Exception
     */
    public function setCreatedAt(): self
    {
        $this->createdAt = new DateTime('Europe/Paris');
        return $this;
    }

    public function getRecallDate(): ?\DateTimeInterface
    {
        return $this->recallDate;
    }

    public function setRecallDate(DateTime $recallDate): self
    {
        $this->recallDate = $recallDate;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getRecallHour()
    {
        return $this->recallHour;
    }

    /**
     * @param mixed $recallHour
     */
    public function setRecallHour($recallHour): void
    {
        $this->recallHour = $recallHour;
    }

    public function getRecallPeriod(): ?RecallPeriod
    {
        return $this->recallPeriod;
    }

    public function setRecallPeriod(?RecallPeriod $recallPeriod): self
    {
        $this->recallPeriod = $recallPeriod;

        return $this;
    }

    public function getFreeComment(): ?string
    {
        return $this->freeComment;
    }

    public function setFreeComment(?string $freeComment): self
    {
        $this->freeComment = $freeComment;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(?string $source): self
    {
        $this->source = $source;

        return $this;
    }

    public function getInternet(): ?string
    {
        return $this->internet;
    }

    public function setInternet(?string $internet): self
    {
        $this->internet = $internet;

        return $this;
    }

    public function getIsProcessed(): ?bool
    {
        return $this->isProcessed;
    }

    public function setIsProcessed(bool $isProcessed): self
    {
        $this->isProcessed = $isProcessed;

        return $this;
    }

    /**
     * @return Collection|CallTransfer[]
     */
    public function getCallTransfers(): Collection
    {
        return $this->callTransfers;
    }

    public function addCallTransfer(CallTransfer $callTransfer): self
    {
        if (!$this->callTransfers->contains($callTransfer)) {
            $this->callTransfers[] = $callTransfer;
            $callTransfer->setReferedCall($this);
        }

        return $this;
    }

    public function removeCallTransfer(CallTransfer $callTransfer): self
    {
        if ($this->callTransfers->contains($callTransfer)) {
            $this->callTransfers->removeElement($callTransfer);
            // set the owning side to null (unless already changed)
            if ($callTransfer->getReferedCall() === $this) {
                $callTransfer->setReferedCall(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CallProcessing[]
     */
    public function getCallProcessings(): Collection
    {
        return $this->callProcessings;
    }

    public function addCallProcessing(CallProcessing $callProcessing): self
    {
        if (!$this->callProcessings->contains($callProcessing)) {

templates/call_process/__supervision.html.twig
{% for call in service.list_to_process %}
    {% include 'call_process/_cell_call_row.html.twig' with {'is_small': true } %}
{% endfor %}
{% for call in service.list_in_process %}
    {% include 'call_process/_cell_call_row.html.twig' with {'is_small': true } %}
{% endfor %}

templates/call_process/_call_row.html.twig
<li class="collection-item" data-date="{{ call.recallDate|date('Ymd') }}{{ call.recallDate|date('Hi') }}" id="call-{{ call.id }}">
    <div class="row call-list-row">
        <div class="col s8">
            <span class="title">{{call.client.civility.name | upper}} {{call.client.name | upper}}</span>
            <p>
                <span class="chip grey lighten-3 grey-text text-darken-4">{{call.client.phone}}</span>
                {% if call.client.phone2 != '' %}
                    <span class="chip grey lighten-3 grey-text text-darken-4">{{ call.client.phone2 }}</span>
                {% endif %}
            </p>
            <p>
                <b>{{call.service.concession.town.name}} > {{call.service.concession.name}} > {{call.service.name}}</b><br>
                {{call.subject.name}} - {{call.comment.name}}<br>
                <span class="free-comment"> {{call.freeComment | raw}}</span>
            </p>
        </div>

        <div class="col s4 left-align ">
            <div class="call-calendar grey lighten-4">
                <div class="call-cal-header {% if call.isUrgent %}urgent{% endif %}">
                    <i class="material-icons ">event_date </i>
                    <span class="call-cal-date">
                        {% if call.recallDate|date('Y-m-d') == date()|date('Y-m-d') %}
                            Aujourd'hui
                        {% elseif call.recallDate|date('Y-m-d') == date('+1days')|date('Y-m-d') %}
                            Demain
                        {% elseif call.recallDate|date('Y-m-d') == date('-1day')|date('Y-m-d') %}
                            Hier
                        {% else %}
                            {{ call.recallDate|date('Y-m-d') | date('d-m-Y')|date('Y-m-d')}}
                        {% endif %}
                    </span>
                </div>
                <div class="call-cal-body">
                    {% if call.isUrgent %}
                    <span class="red-text">urgent</span>
                    {% else %}
                    <span class="grey-text text-darken-4">{{call.recallPeriod.name}} {{call.recallHour|date('H:i')}}</span>
                    {% endif %}
                </div>
                <div class="call-cal-action">
                    <a class="{% if call.isUrgent %}red{% else %} green darken-3 {% endif %} call-treatment-btn" href="#" data-call="{{ call.id }}" id="treatment-btn-{{ call.id }}">Traiter</a>
                </div>
            </div>
        </div>
    </div>
</li>

templates/call_process/_call_row_inside.html.twig
    <div class="row call-list-row">
        <div class="col s8">
            <span class="title">{{call.client.civility.name | upper }} {{call.client.name | upper }}</span>
            <p>
                <span class="chip grey lighten-3 grey-text text-darken-4">{{call.client.phone}}</span>
                {% if call.client.phone2 != '' %}
                    <span class="chip grey lighten-3 grey-text text-darken-4">{{ call.client.phone2 }}</span>
                {% endif %}
            </p>
            <p>
                <b>{{call.service.concession.town.name}} > {{call.service.concession.name}} > {{call.service.name}}</b><br>
                {{call.subject.name}} - {{call.comment.name}}<br>
                <span class="free-comment"> {{call.freeComment | raw}}</span>
            </p>
        </div>

        <div class="col s4 left-align ">
            <div class="call-calendar grey lighten-4">
                <div class="call-cal-header {% if call.isUrgent %}urgent{% endif %}">
                    <i class="material-icons ">event_date </i>
                    <span class="call-cal-date">
                       {{call.recallDate|formatDate}}
                    </span>
                </div>
                <div class="call-cal-body">
                    {% if call.isUrgent %}
                    <span class="red-text">urgent</span>
                    {% else %}
                    <span class="grey-text text-darken-4">{{call.recallPeriod.name}} {{call.recallHour|date('H:i')}}</span>
                    {% endif %}
                </div>
                <div class="call-cal-action">
                    <a class="{% if call.isUrgent %}red{% else %} green darken-3 {% endif %} call-treatment-btn" href="#" data-call="{{ call.id }}" id="treatment-btn-{{ call.id }}">Traiter</a>
                </div>
            </div>
        </div>
    </div>

templates/call_process/_cell_call_row.html.twig
<li
        class="collection-item cell-item {{ is_small is defined ? 'small' : '' }}"
        data-date="{{ call.recallDate|date('Ymd') }}{{ call.recallDate|date('Hi') }}"
        id="call-{{ call.id }}"
        data-status="{% if app.request.get('_route') == 'user_home' %}new{% else %} inprocess{% endif %}"
>
    <div class="row call-list-row-cell">
        <div class="col s10 ">

            <div class="row">
                <div class="col s4">
                    <small>
                    créé
                    <span class="bolder">
                            {{call.createdAt|dateName}} à {{ call.createdAt|timeFormat}}
                    </span>
                        {% if call.author %}
                            {% if call.author.firstname == 'INTERNET' %}
                                par <span class="bolder">{{call.author.firstName}}</span>
                            {% else %}
                            par <span class="bolder">{{call.author.service.concession.name}} - {{call.author.service.name}}</span>
                            {% endif %}
                        {% endif %}
                    </small>
                    {% if call.callTransfers is not empty %}
                        <i class="material-icons left tooltipped" data-position="right" data-tooltip="<div class='left-align'>
                        {% for transfer in call.callTransfers|reverse %}
                            <span class='history-line'>
                            - Transféré par {{ transfer.byWhom.firstName }} {{ transfer.byWhom.lastName }} {{ transfer.createdAt|dateName }} à {{ transfer.createdAt|timeFormat }}
                            <span>
                            <br>
                        {% endfor %}
                        </div>
                        ">description</i>
                    {% endif %}
                    {% if (is_granted('ROLE_ADMIN')) %}
                        <a
                                href="#"
                                class="white-text left tooltipped delete-call"
                                data-call="{{ call.id }}"
                                data-position="top"
                                data-tooltip="supprimer cet appel"
                                data-status="{% if app.request.get('_route') == 'user_home' %}new{% else %}inprocess{% endif %}"
                        >
                            <i class="material-icons red-text">delete_forever</i>
                        </a>
                    {% endif %}
                </div>
                <div class="col s8 recipient-zone">
                    {% if call.recipient and call.recipient.service.users is not empty %}
                        <div class="list-dest hide" id="users-in-service-{{ call.id }}">
                            <span class="before">Transférer à ...
                                <a href="#" data-has-click-event="0" class="close-list secondary-content white-text" data-target="users-in-service-{{ call.id }}"><i class="material-icons">close</i></a>
                            </span>
                            <ul class="">
                                {%  for user in call.recipient.service.users %}
                                    <li class="dest-item">
                                        <a href="#" data-has-click-event="0" class="recipients-to-transfer" data-service="{{ call.recipient.service.id }}" data-in-slider="1" data-for="{{ user.id }}" data-call="{{ call.id }}">{{user.firstname}} {{user.lastname}} </a>
                                        <i class="material-icons white-text secondary-content">phone_forwarded</i>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% if call.recipient %}
                        <span class="chip flow-text black-text grey lighten-2 recipient-changer" data-has-click-event="0" data-call="{{ call.id }}">
                            <i class="material-icons left ">person</i>
                            {{ call.recipient.firstname }} {{ call.recipient.lastname }}
                        </span>
                        <span class="place-name">
                        <i class="material-icons tiny">home</i>
                        {{call.recipient.service.concession.name}}
                    </span>
                        <span class="place-name service-name">
                        <i class="material-icons tiny">settings</i>
                        {{ call.recipient.service.name }}
                            {% if call.recipient %}
                                <br><a data-service="{{ call.recipient.service.id }}" class="orange darken-3 call-transfer-btn btn-rounded mgl30" href="#" data-call="{{ call.id }}" id="treatment-btn-{{ call.id }}" data-in-slider="{{ is_small is defined ? '1' : '0' }}">
                                    Transférer
                                </a>
                            {% endif %}
                    </span>
                    {% else %}
                        {% if user is defined %}
                            {% if user.canBeRecipient %}
                                <a href="{{ path('take_call', {'id' : call.id, 'user' : app.user.id}) }}" class="btn cyan white-text">Prendre en charge</a>
                                {%  if isHead == true and user != connectedUser%}
                                    <a href="{{ path('take_call', {'id' : call.id, 'user' : user.id}) }}"
                                       class="btn orange white-text">
                                        Attribuer à {{ user.firstname | slice(0,1) | upper }}. {{ user.lastname | upper }}
                                    </a>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            <a href="{{ path('take_call', {'id' : call.id, 'user' : app.user.id }) }}" class="btn cyan white-text">Prendre en charge</a>
                        {% endif %}
                        <span class="place-name">
                        <i class="material-icons tiny">home</i>
                        {{call.service.concession.name}}
                    </span>
                        <span class="place-name service-name">
                        <i class="material-icons tiny">settings</i>
                        {{ call.service.name }}
                            {% if call.recipient %}
                                <a class="orange darken-3 call-transfer-btn btn-rounded mgl30" href="#" data-call="{{ call.id }}" id="treatment-btn-{{ call.id }}">Transférer</a>
                            {% endif %}
                    </span>
                    {% endif %}

                </div>
            </div>

            <div class="row">
               <div class="col s4">
                    <span class="title">
                        {{call.client.civility.name | upper}} {{call.client.name | upper}}
                        {% if call.client.email != '' %}
                            <span class="mgl30"><i class="material-icons tooltipped grey-text text-darken-3 tiny copy-tooltip" data-position="top" data-email="{{call.client.email}}" data-tooltip="{{call.client.email}} / cliquer l'icone pour copier">mail</i></span>
                        {% endif %}
                    </span>
               </div>
               <div class="col s4 d-flex flex-items-center">
                   <i class="material-icons left grey-text">label</i>
                   {{ call.subject.name }}
               </div>
               <div class="col s4 d-flex flex-items-center">
                   <i class="material-icons left grey-text">label</i>
                   {{ call.comment.name }}
               </div>
           </div>

            <div class="row">
                <div class="col s4">
                    <span class="chip ">{{call.client.phone|phoneNumber}}</span>
                </div>
                <div class="col s8">
                    <em>{{ call.freeComment | raw }}</em>
                </div>
            </div>
            <div class="row">
                <div class="col s4">
                    {% if call.client.phone2 is defined and call.client.phone2 is not null and call.client.phone2 is not empty %}
                        <span class="chip">{{ call.client.phone2|phoneNumber }}</span>
                    {% endif %}
                </div>
                <div class="col s5" id="call-history-{{ call.id }}">
                    {% for process in call.callProcessings|reverse[:1] %}
                            <span class="chip {{process.stepColors.bgColor}} black-text">{{process.stepColors.stepName | raw }}</span>
                            <span class="bolder">
                                {{ process.createdAt | dateName }}
                                à {{ process.createdAt | timeFormat }}
                            </span>
                    {% endfor %}
                </div>
                <div class="col s3 right-align">
                    <i class="material-icons small left">directions_car</i> <span class="immat left">{{ call.vehicle.immatriculation | upper }}</span>
                    {% if call.vehicle.hasCome is constant('App\\Entity\\Vehicle::TRISWITCH_YES_VALUE') %}
                        <i class="material-icons left light-green-text tooltipped small-more" data-tooltip="Déja venu à l'atelier" data-position="top">build</i>
                    {% elseif call.vehicle.hasCome is constant('App\\Entity\\Vehicle::TRISWITCH_NO_VALUE') %}
                        <i class="material-icons left red-text tooltipped small-more" data-tooltip="Jamais venu à l'atelier" data-position="top">build</i>
                    {% endif %}
                    {% if call.vehicle.chassis %}
                       <span class="d-block left chassis"><span class="bolder">Chassis : </span>{{ call.vehicle.chassis }}</span>
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="col s2 left-align ">
            <div class="call-calendar small grey lighten-4">

                <div
                        class="alert-callback tooltipped {% if call.clientCallback == 0 %} hide {% endif %}"
                        data-position="top"
                        data-tooltip="rappel(s) du client"
                        id="client-callback-{{ call.id }}"
                >
                    {{ call.clientCallback }}
                </div>
                <div class="d-flex flex-items-center flex-justify-center call-cal-header {% if call.lastProcessColor is not empty %} {{ call.lastProcessColor.class}} {% endif %}{% if call.isUrgent %}urgent{% endif %}" id="cal-head-{{ call.id }}">
                    <i class="material-icons ">event_date </i>
                    <span class="call-cal-date">
                        {{ call.recallDate|dateName(is_small is defined) }}
                    </span>
                </div>
                <div class="call-cal-body">
                    <span class="bolder">
                    {% if call.isUrgent %}
                        <span class="red-text" id="recall-urgent-{{ call.id }}">urgent</span>
                    {% else %}
                        <span class="grey-text text-darken-4">{{call.recallPeriod.name}} {{call.recallHour|timeFormat}}</span>
                    {% endif %}
                    </span>
                </div>
                <div class="call-cal-action">
                    {% if call.recipient is not null %}
                    <a class="{% if call.isUrgent %}urgent{% else %} green darken-3 {% endif %} call-treatment-btn" href="#" data-service="{{ call.recipient.service.id }}" data-call="{{ call.id }}" id="treatment-btn-{{ call.id }}" data-in-slider="{{ is_small is defined ? '1' : '0' }}">
                        Traiter
                    </a>
               {% endif %}
                </div>
            </div>
        </div>
    </div>
</li>

templates/call_process/_form_transfer.html.twig
{{ form_start(form,{'attr': {'id': 'form-transfer' }}, {'action': path('call_transfer_do', {callId : call.id})}) }}
<div class="row">
    <div class="col input-field s12">
        {{ form_widget(form.city) }}
    </div>
    <div class="col input-field s12" id="transfer-concession">
        {{ form_widget(form.concession) }}
    </div>
    <div class="col input-field s12"  id="transfer-service">
        {{ form_widget(form.service) }}
    </div>
    <div class="col input-field s12"  id="transfer-recipient">
        {{ form_widget(form.recipient) }}
    </div>
    <div class="col input-field s12">
        {{ form_widget(form.commentTransfer) }}
    </div>
</div>
<div class="row">
    <div class="col s6">
        <input type="submit" value="transférer" class="btn light-blue" id="transfer-call-btn" data-call="{{ call.id }}">
    </div>
    <div class="col s6">
        <div class="progress grey lighten-3 hide" id="transfer-preloader">
            <div class="indeterminate light-blue"></div>
        </div>
    </div>
</div>
{{ form_end(form) }}

templates/call_process/_new_calls.html.twig
{% for call in calls %}
    {% include 'call_process/_cell_call_row.html.twig' %}
{% else %}
null
{% endfor %}

templates/call_process/call_process.html.twig
<div class="row">
    <h4>Traiter un appel</h4>
</div>
<div class="row">
    <div class="col s6">
        <div class="col s12">
            <span class="title"><h5>{{call.client.civility.name | upper }} {{call.client.name | upper }}</h5></span>
            <p>
                <span class="chip">{{call.client.phone|phoneNumber}}</span><br>
                {% if call.client.phone2 is defined and call.client.phone2 is not null and call.client.phone2 is not empty %}
                <span class="chip">{{ call.client.phone2|phoneNumber }}</span>
                {% endif %}
            </p>
            <p>
                <b> {{ call.recipient.service.concession.town.name }}<br>
                    {{ call.recipient.service.concession.name }}<br>
                    {{ call.recipient.service.name }}</b><br>
                <small>{{call.subject.name}} - {{call.comment.name}}</small><br>
            </p>
        </div>
    </div>
    <div class="col s6">
        <div class="row">
            {% include 'call_process/_form.html.twig' %}
        </div>
        <div class="row">
            {% if call.callProcessings %}
                {% for process in call.callProcessings|reverse %}
                    <div class="col s12">
                        <table class="call-stepper">
                            <tr class="call-step">
                                <td>
                                    <b>
                                        {{process.createdAt|dateName}}
                                    </b>
                                </td>
                                <td> à {{ process.createdAt|timeFormat }}</td>
                                <td class="{{ process.stepColors.color }}">{{ process.contactType.name }}</td>
                                <td>{{ process.comment }}</td>
                            </tr>
                        </table>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

templates/call_process/call_transfer.html.twig
<div class="row">
    <h4>Transférer un appel</h4>
</div>
<div class="row">
    <div class="col s6">
        <div class="col s12">
            <span class="title"><h5>{{call.client.name | upper}}</h5></span>
            <p>
                {{call.client.phone}}<br>
                {{ call.client.phone2 }}
            </p>
            <p>
                <b>{{ call.recipient.service.concession.town.name }} > {{ call.recipient.service.concession.name }} > {{ call.recipient.service.name }}</b><br>
                <small>{{call.subject.name}} - {{call.comment.name}}</small><br>
            </p>

            <table>
                {% for process in call.callProcessings|reverse %}
                    <div class="d-flex gap-10 mb-10">
                        <span class="chip {{process.stepColors.bgColor}} black-text">{{process.stepColors.stepName | raw }}</span>
                        <span class="bolder">
                            {{ process.createdAt | dateName }} à {{ process.createdAt | timeFormat }}
                            {% if process.comment %}
                                <br><small class="m-0 p-0 no-bold">
                                    {{ process.comment }}
                                </small>
                            {% endif %}
                        </span>

                    </div>
                {% endfor %}
            </table>

        </div>
    </div>
    <div class="col s6">
        <div class="row">
            {% include 'call_process/_form_transfer.html.twig' %}
        </div>
    </div>
</div>